/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.ace.qa.hms.sb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.um.ace.qa.hms.sb.model.room_new;
import com.um.ace.qa.hms.sb.model.room_newModel;
import com.um.ace.qa.hms.sb.model.room_newSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the room_new service. Represents a row in the &quot;hms_room_new&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>room_newModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link room_newImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see room_newImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class room_newModelImpl
	extends BaseModelImpl<room_new> implements room_newModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a room_new model instance should use the <code>room_new</code> interface instead.
	 */
	public static final String TABLE_NAME = "hms_room_new";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"roomID", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"roomSize", Types.VARCHAR}, {"images", Types.VARCHAR},
		{"roomNo", Types.BIGINT}, {"roomName", Types.VARCHAR},
		{"facilities", Types.VARCHAR}, {"facilities2", Types.VARCHAR},
		{"facilities3", Types.VARCHAR}, {"facilities4", Types.VARCHAR},
		{"payment", Types.BIGINT}, {"carddetails", Types.BIGINT},
		{"cvv", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roomID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("roomSize", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("images", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roomNo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roomName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities4", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("payment", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("carddetails", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cvv", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table hms_room_new (uuid_ VARCHAR(75) null,roomID LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,roomSize VARCHAR(75) null,images VARCHAR(75) null,roomNo LONG,roomName VARCHAR(75) null,facilities VARCHAR(75) null,facilities2 VARCHAR(75) null,facilities3 VARCHAR(75) null,facilities4 VARCHAR(75) null,payment LONG,carddetails LONG,cvv LONG)";

	public static final String TABLE_SQL_DROP = "drop table hms_room_new";

	public static final String ORDER_BY_JPQL = " ORDER BY room_new.roomNo ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY hms_room_new.roomNo ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ROOMNO_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static room_new toModel(room_newSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		room_new model = new room_newImpl();

		model.setUuid(soapModel.getUuid());
		model.setRoomID(soapModel.getRoomID());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setRoomSize(soapModel.getRoomSize());
		model.setImages(soapModel.getImages());
		model.setRoomNo(soapModel.getRoomNo());
		model.setRoomName(soapModel.getRoomName());
		model.setFacilities(soapModel.getFacilities());
		model.setFacilities2(soapModel.getFacilities2());
		model.setFacilities3(soapModel.getFacilities3());
		model.setFacilities4(soapModel.getFacilities4());
		model.setPayment(soapModel.getPayment());
		model.setCarddetails(soapModel.getCarddetails());
		model.setCvv(soapModel.getCvv());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<room_new> toModels(room_newSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<room_new> models = new ArrayList<room_new>(soapModels.length);

		for (room_newSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public room_newModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _roomID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoomID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _roomID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return room_new.class;
	}

	@Override
	public String getModelClassName() {
		return room_new.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<room_new, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<room_new, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room_new, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((room_new)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<room_new, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<room_new, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(room_new)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<room_new, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<room_new, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<room_new, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<room_new, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<room_new, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<room_new, Object>>();
		Map<String, BiConsumer<room_new, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<room_new, ?>>();

		attributeGetterFunctions.put("uuid", room_new::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<room_new, String>)room_new::setUuid);
		attributeGetterFunctions.put("roomID", room_new::getRoomID);
		attributeSetterBiConsumers.put(
			"roomID", (BiConsumer<room_new, Long>)room_new::setRoomID);
		attributeGetterFunctions.put("groupId", room_new::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<room_new, Long>)room_new::setGroupId);
		attributeGetterFunctions.put("companyId", room_new::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<room_new, Long>)room_new::setCompanyId);
		attributeGetterFunctions.put("userId", room_new::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<room_new, Long>)room_new::setUserId);
		attributeGetterFunctions.put("userName", room_new::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<room_new, String>)room_new::setUserName);
		attributeGetterFunctions.put("createDate", room_new::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<room_new, Date>)room_new::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", room_new::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<room_new, Date>)room_new::setModifiedDate);
		attributeGetterFunctions.put("roomSize", room_new::getRoomSize);
		attributeSetterBiConsumers.put(
			"roomSize", (BiConsumer<room_new, String>)room_new::setRoomSize);
		attributeGetterFunctions.put("images", room_new::getImages);
		attributeSetterBiConsumers.put(
			"images", (BiConsumer<room_new, String>)room_new::setImages);
		attributeGetterFunctions.put("roomNo", room_new::getRoomNo);
		attributeSetterBiConsumers.put(
			"roomNo", (BiConsumer<room_new, Long>)room_new::setRoomNo);
		attributeGetterFunctions.put("roomName", room_new::getRoomName);
		attributeSetterBiConsumers.put(
			"roomName", (BiConsumer<room_new, String>)room_new::setRoomName);
		attributeGetterFunctions.put("facilities", room_new::getFacilities);
		attributeSetterBiConsumers.put(
			"facilities",
			(BiConsumer<room_new, String>)room_new::setFacilities);
		attributeGetterFunctions.put("facilities2", room_new::getFacilities2);
		attributeSetterBiConsumers.put(
			"facilities2",
			(BiConsumer<room_new, String>)room_new::setFacilities2);
		attributeGetterFunctions.put("facilities3", room_new::getFacilities3);
		attributeSetterBiConsumers.put(
			"facilities3",
			(BiConsumer<room_new, String>)room_new::setFacilities3);
		attributeGetterFunctions.put("facilities4", room_new::getFacilities4);
		attributeSetterBiConsumers.put(
			"facilities4",
			(BiConsumer<room_new, String>)room_new::setFacilities4);
		attributeGetterFunctions.put("payment", room_new::getPayment);
		attributeSetterBiConsumers.put(
			"payment", (BiConsumer<room_new, Long>)room_new::setPayment);
		attributeGetterFunctions.put("carddetails", room_new::getCarddetails);
		attributeSetterBiConsumers.put(
			"carddetails",
			(BiConsumer<room_new, Long>)room_new::setCarddetails);
		attributeGetterFunctions.put("cvv", room_new::getCvv);
		attributeSetterBiConsumers.put(
			"cvv", (BiConsumer<room_new, Long>)room_new::setCvv);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRoomID() {
		return _roomID;
	}

	@Override
	public void setRoomID(long roomID) {
		_roomID = roomID;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getRoomSize() {
		if (_roomSize == null) {
			return "";
		}
		else {
			return _roomSize;
		}
	}

	@Override
	public void setRoomSize(String roomSize) {
		_roomSize = roomSize;
	}

	@JSON
	@Override
	public String getImages() {
		if (_images == null) {
			return "";
		}
		else {
			return _images;
		}
	}

	@Override
	public void setImages(String images) {
		_images = images;
	}

	@JSON
	@Override
	public long getRoomNo() {
		return _roomNo;
	}

	@Override
	public void setRoomNo(long roomNo) {
		_columnBitmask = -1L;

		_roomNo = roomNo;
	}

	@JSON
	@Override
	public String getRoomName() {
		if (_roomName == null) {
			return "";
		}
		else {
			return _roomName;
		}
	}

	@Override
	public void setRoomName(String roomName) {
		_roomName = roomName;
	}

	@JSON
	@Override
	public String getFacilities() {
		if (_facilities == null) {
			return "";
		}
		else {
			return _facilities;
		}
	}

	@Override
	public void setFacilities(String facilities) {
		_facilities = facilities;
	}

	@JSON
	@Override
	public String getFacilities2() {
		if (_facilities2 == null) {
			return "";
		}
		else {
			return _facilities2;
		}
	}

	@Override
	public void setFacilities2(String facilities2) {
		_facilities2 = facilities2;
	}

	@JSON
	@Override
	public String getFacilities3() {
		if (_facilities3 == null) {
			return "";
		}
		else {
			return _facilities3;
		}
	}

	@Override
	public void setFacilities3(String facilities3) {
		_facilities3 = facilities3;
	}

	@JSON
	@Override
	public String getFacilities4() {
		if (_facilities4 == null) {
			return "";
		}
		else {
			return _facilities4;
		}
	}

	@Override
	public void setFacilities4(String facilities4) {
		_facilities4 = facilities4;
	}

	@JSON
	@Override
	public long getPayment() {
		return _payment;
	}

	@Override
	public void setPayment(long payment) {
		_payment = payment;
	}

	@JSON
	@Override
	public long getCarddetails() {
		return _carddetails;
	}

	@Override
	public void setCarddetails(long carddetails) {
		_carddetails = carddetails;
	}

	@JSON
	@Override
	public long getCvv() {
		return _cvv;
	}

	@Override
	public void setCvv(long cvv) {
		_cvv = cvv;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(room_new.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), room_new.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public room_new toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (room_new)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		room_newImpl room_newImpl = new room_newImpl();

		room_newImpl.setUuid(getUuid());
		room_newImpl.setRoomID(getRoomID());
		room_newImpl.setGroupId(getGroupId());
		room_newImpl.setCompanyId(getCompanyId());
		room_newImpl.setUserId(getUserId());
		room_newImpl.setUserName(getUserName());
		room_newImpl.setCreateDate(getCreateDate());
		room_newImpl.setModifiedDate(getModifiedDate());
		room_newImpl.setRoomSize(getRoomSize());
		room_newImpl.setImages(getImages());
		room_newImpl.setRoomNo(getRoomNo());
		room_newImpl.setRoomName(getRoomName());
		room_newImpl.setFacilities(getFacilities());
		room_newImpl.setFacilities2(getFacilities2());
		room_newImpl.setFacilities3(getFacilities3());
		room_newImpl.setFacilities4(getFacilities4());
		room_newImpl.setPayment(getPayment());
		room_newImpl.setCarddetails(getCarddetails());
		room_newImpl.setCvv(getCvv());

		room_newImpl.resetOriginalValues();

		return room_newImpl;
	}

	@Override
	public int compareTo(room_new room_new) {
		int value = 0;

		if (getRoomNo() < room_new.getRoomNo()) {
			value = -1;
		}
		else if (getRoomNo() > room_new.getRoomNo()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof room_new)) {
			return false;
		}

		room_new room_new = (room_new)obj;

		long primaryKey = room_new.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		room_newModelImpl room_newModelImpl = this;

		room_newModelImpl._originalUuid = room_newModelImpl._uuid;

		room_newModelImpl._originalGroupId = room_newModelImpl._groupId;

		room_newModelImpl._setOriginalGroupId = false;

		room_newModelImpl._originalCompanyId = room_newModelImpl._companyId;

		room_newModelImpl._setOriginalCompanyId = false;

		room_newModelImpl._setModifiedDate = false;

		room_newModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<room_new> toCacheModel() {
		room_newCacheModel room_newCacheModel = new room_newCacheModel();

		room_newCacheModel.uuid = getUuid();

		String uuid = room_newCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			room_newCacheModel.uuid = null;
		}

		room_newCacheModel.roomID = getRoomID();

		room_newCacheModel.groupId = getGroupId();

		room_newCacheModel.companyId = getCompanyId();

		room_newCacheModel.userId = getUserId();

		room_newCacheModel.userName = getUserName();

		String userName = room_newCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			room_newCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			room_newCacheModel.createDate = createDate.getTime();
		}
		else {
			room_newCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			room_newCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			room_newCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		room_newCacheModel.roomSize = getRoomSize();

		String roomSize = room_newCacheModel.roomSize;

		if ((roomSize != null) && (roomSize.length() == 0)) {
			room_newCacheModel.roomSize = null;
		}

		room_newCacheModel.images = getImages();

		String images = room_newCacheModel.images;

		if ((images != null) && (images.length() == 0)) {
			room_newCacheModel.images = null;
		}

		room_newCacheModel.roomNo = getRoomNo();

		room_newCacheModel.roomName = getRoomName();

		String roomName = room_newCacheModel.roomName;

		if ((roomName != null) && (roomName.length() == 0)) {
			room_newCacheModel.roomName = null;
		}

		room_newCacheModel.facilities = getFacilities();

		String facilities = room_newCacheModel.facilities;

		if ((facilities != null) && (facilities.length() == 0)) {
			room_newCacheModel.facilities = null;
		}

		room_newCacheModel.facilities2 = getFacilities2();

		String facilities2 = room_newCacheModel.facilities2;

		if ((facilities2 != null) && (facilities2.length() == 0)) {
			room_newCacheModel.facilities2 = null;
		}

		room_newCacheModel.facilities3 = getFacilities3();

		String facilities3 = room_newCacheModel.facilities3;

		if ((facilities3 != null) && (facilities3.length() == 0)) {
			room_newCacheModel.facilities3 = null;
		}

		room_newCacheModel.facilities4 = getFacilities4();

		String facilities4 = room_newCacheModel.facilities4;

		if ((facilities4 != null) && (facilities4.length() == 0)) {
			room_newCacheModel.facilities4 = null;
		}

		room_newCacheModel.payment = getPayment();

		room_newCacheModel.carddetails = getCarddetails();

		room_newCacheModel.cvv = getCvv();

		return room_newCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<room_new, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<room_new, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room_new, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((room_new)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<room_new, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<room_new, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room_new, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((room_new)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		room_new.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		room_new.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _roomID;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _roomSize;
	private String _images;
	private long _roomNo;
	private String _roomName;
	private String _facilities;
	private String _facilities2;
	private String _facilities3;
	private String _facilities4;
	private long _payment;
	private long _carddetails;
	private long _cvv;
	private long _columnBitmask;
	private room_new _escapedModel;

}