/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.um.ace.qa.hms.sb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.um.ace.qa.hms.sb.model.room;
import com.um.ace.qa.hms.sb.model.roomModel;
import com.um.ace.qa.hms.sb.model.roomSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the room service. Represents a row in the &quot;hms_room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>roomModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link roomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see roomImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class roomModelImpl extends BaseModelImpl<room> implements roomModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a room model instance should use the <code>room</code> interface instead.
	 */
	public static final String TABLE_NAME = "hms_room";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"roomID", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"roomSize", Types.VARCHAR}, {"images", Types.VARCHAR},
		{"roomNo", Types.BIGINT}, {"roomName", Types.VARCHAR},
		{"facilities", Types.VARCHAR}, {"facilities2", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roomID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("roomSize", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("images", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roomNo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roomName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facilities2", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table hms_room (uuid_ VARCHAR(75) null,roomID LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,roomSize VARCHAR(75) null,images VARCHAR(75) null,roomNo LONG,roomName VARCHAR(75) null,facilities VARCHAR(75) null,facilities2 VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table hms_room";

	public static final String ORDER_BY_JPQL = " ORDER BY room.roomNo ASC";

	public static final String ORDER_BY_SQL = " ORDER BY hms_room.roomNo ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ROOMNO_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static room toModel(roomSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		room model = new roomImpl();

		model.setUuid(soapModel.getUuid());
		model.setRoomID(soapModel.getRoomID());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setRoomSize(soapModel.getRoomSize());
		model.setImages(soapModel.getImages());
		model.setRoomNo(soapModel.getRoomNo());
		model.setRoomName(soapModel.getRoomName());
		model.setFacilities(soapModel.getFacilities());
		model.setFacilities2(soapModel.getFacilities2());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<room> toModels(roomSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<room> models = new ArrayList<room>(soapModels.length);

		for (roomSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public roomModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _roomID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoomID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _roomID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return room.class;
	}

	@Override
	public String getModelClassName() {
		return room.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<room, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<room, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((room)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<room, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<room, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((room)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<room, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<room, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<room, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<room, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<room, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<room, Object>>();
		Map<String, BiConsumer<room, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<room, ?>>();

		attributeGetterFunctions.put("uuid", room::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<room, String>)room::setUuid);
		attributeGetterFunctions.put("roomID", room::getRoomID);
		attributeSetterBiConsumers.put(
			"roomID", (BiConsumer<room, Long>)room::setRoomID);
		attributeGetterFunctions.put("groupId", room::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<room, Long>)room::setGroupId);
		attributeGetterFunctions.put("companyId", room::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<room, Long>)room::setCompanyId);
		attributeGetterFunctions.put("userId", room::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<room, Long>)room::setUserId);
		attributeGetterFunctions.put("userName", room::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<room, String>)room::setUserName);
		attributeGetterFunctions.put("createDate", room::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<room, Date>)room::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", room::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<room, Date>)room::setModifiedDate);
		attributeGetterFunctions.put("roomSize", room::getRoomSize);
		attributeSetterBiConsumers.put(
			"roomSize", (BiConsumer<room, String>)room::setRoomSize);
		attributeGetterFunctions.put("images", room::getImages);
		attributeSetterBiConsumers.put(
			"images", (BiConsumer<room, String>)room::setImages);
		attributeGetterFunctions.put("roomNo", room::getRoomNo);
		attributeSetterBiConsumers.put(
			"roomNo", (BiConsumer<room, Long>)room::setRoomNo);
		attributeGetterFunctions.put("roomName", room::getRoomName);
		attributeSetterBiConsumers.put(
			"roomName", (BiConsumer<room, String>)room::setRoomName);
		attributeGetterFunctions.put("facilities", room::getFacilities);
		attributeSetterBiConsumers.put(
			"facilities", (BiConsumer<room, String>)room::setFacilities);
		attributeGetterFunctions.put("facilities2", room::getFacilities2);
		attributeSetterBiConsumers.put(
			"facilities2", (BiConsumer<room, String>)room::setFacilities2);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRoomID() {
		return _roomID;
	}

	@Override
	public void setRoomID(long roomID) {
		_roomID = roomID;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getRoomSize() {
		if (_roomSize == null) {
			return "";
		}
		else {
			return _roomSize;
		}
	}

	@Override
	public void setRoomSize(String roomSize) {
		_roomSize = roomSize;
	}

	@JSON
	@Override
	public String getImages() {
		if (_images == null) {
			return "";
		}
		else {
			return _images;
		}
	}

	@Override
	public void setImages(String images) {
		_images = images;
	}

	@JSON
	@Override
	public long getRoomNo() {
		return _roomNo;
	}

	@Override
	public void setRoomNo(long roomNo) {
		_columnBitmask = -1L;

		_roomNo = roomNo;
	}

	@JSON
	@Override
	public String getRoomName() {
		if (_roomName == null) {
			return "";
		}
		else {
			return _roomName;
		}
	}

	@Override
	public void setRoomName(String roomName) {
		_roomName = roomName;
	}

	@JSON
	@Override
	public String getFacilities() {
		if (_facilities == null) {
			return "";
		}
		else {
			return _facilities;
		}
	}

	@Override
	public void setFacilities(String facilities) {
		_facilities = facilities;
	}

	@JSON
	@Override
	public String getFacilities2() {
		if (_facilities2 == null) {
			return "";
		}
		else {
			return _facilities2;
		}
	}

	@Override
	public void setFacilities2(String facilities2) {
		_facilities2 = facilities2;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(room.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), room.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public room toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (room)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		roomImpl roomImpl = new roomImpl();

		roomImpl.setUuid(getUuid());
		roomImpl.setRoomID(getRoomID());
		roomImpl.setGroupId(getGroupId());
		roomImpl.setCompanyId(getCompanyId());
		roomImpl.setUserId(getUserId());
		roomImpl.setUserName(getUserName());
		roomImpl.setCreateDate(getCreateDate());
		roomImpl.setModifiedDate(getModifiedDate());
		roomImpl.setRoomSize(getRoomSize());
		roomImpl.setImages(getImages());
		roomImpl.setRoomNo(getRoomNo());
		roomImpl.setRoomName(getRoomName());
		roomImpl.setFacilities(getFacilities());
		roomImpl.setFacilities2(getFacilities2());

		roomImpl.resetOriginalValues();

		return roomImpl;
	}

	@Override
	public int compareTo(room room) {
		int value = 0;

		if (getRoomNo() < room.getRoomNo()) {
			value = -1;
		}
		else if (getRoomNo() > room.getRoomNo()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof room)) {
			return false;
		}

		room room = (room)obj;

		long primaryKey = room.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		roomModelImpl roomModelImpl = this;

		roomModelImpl._originalUuid = roomModelImpl._uuid;

		roomModelImpl._originalGroupId = roomModelImpl._groupId;

		roomModelImpl._setOriginalGroupId = false;

		roomModelImpl._originalCompanyId = roomModelImpl._companyId;

		roomModelImpl._setOriginalCompanyId = false;

		roomModelImpl._setModifiedDate = false;

		roomModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<room> toCacheModel() {
		roomCacheModel roomCacheModel = new roomCacheModel();

		roomCacheModel.uuid = getUuid();

		String uuid = roomCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			roomCacheModel.uuid = null;
		}

		roomCacheModel.roomID = getRoomID();

		roomCacheModel.groupId = getGroupId();

		roomCacheModel.companyId = getCompanyId();

		roomCacheModel.userId = getUserId();

		roomCacheModel.userName = getUserName();

		String userName = roomCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			roomCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			roomCacheModel.createDate = createDate.getTime();
		}
		else {
			roomCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			roomCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			roomCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		roomCacheModel.roomSize = getRoomSize();

		String roomSize = roomCacheModel.roomSize;

		if ((roomSize != null) && (roomSize.length() == 0)) {
			roomCacheModel.roomSize = null;
		}

		roomCacheModel.images = getImages();

		String images = roomCacheModel.images;

		if ((images != null) && (images.length() == 0)) {
			roomCacheModel.images = null;
		}

		roomCacheModel.roomNo = getRoomNo();

		roomCacheModel.roomName = getRoomName();

		String roomName = roomCacheModel.roomName;

		if ((roomName != null) && (roomName.length() == 0)) {
			roomCacheModel.roomName = null;
		}

		roomCacheModel.facilities = getFacilities();

		String facilities = roomCacheModel.facilities;

		if ((facilities != null) && (facilities.length() == 0)) {
			roomCacheModel.facilities = null;
		}

		roomCacheModel.facilities2 = getFacilities2();

		String facilities2 = roomCacheModel.facilities2;

		if ((facilities2 != null) && (facilities2.length() == 0)) {
			roomCacheModel.facilities2 = null;
		}

		return roomCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<room, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<room, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((room)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<room, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<room, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<room, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((room)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = room.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		room.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _roomID;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _roomSize;
	private String _images;
	private long _roomNo;
	private String _roomName;
	private String _facilities;
	private String _facilities2;
	private long _columnBitmask;
	private room _escapedModel;

}